<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class DeleteUnusedColumnsFromChasseursTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('chasseurs', function (Blueprint $table) {
            $table->dropColumn('h2_content');
            $table->dropColumn('p_content');
            $table->dropColumn('h3_content_1');
            $table->dropColumn('h3_content_2');
            $table->dropColumn('h3_content_3');
            $table->dropColumn('h3_content_4');
            $table->dropColumn('h3_content_5');
            $table->dropColumn('h3_content_6');
            $table->dropColumn('h3_content_7');
            $table->dropColumn('h3_content_8');
            $table->dropColumn('h3_content_9');
            $table->dropColumn('h3_content_10');
            $table->dropColumn('h3_content_11');
            $table->dropColumn('h3_content_12');
            $table->dropColumn('h3_content_13');
            $table->dropColumn('h3_content_14');
            $table->dropColumn('h3_content_15');
            $table->dropColumn('h3_content_16');
            $table->dropColumn('h3_content_17');
            $table->dropColumn('h3_content_18');
            $table->dropColumn('h3_content_19');
            $table->dropColumn('h3_content_20');
            $table->dropColumn('p_content_1');
            $table->dropColumn('p_content_2');
            $table->dropColumn('p_content_3');
            $table->dropColumn('p_content_4');
            $table->dropColumn('p_content_5');
            $table->dropColumn('p_content_6');
            $table->dropColumn('p_content_7');
            $table->dropColumn('p_content_8');
            $table->dropColumn('p_content_9');
            $table->dropColumn('p_content_10');
            $table->dropColumn('p_content_11');
            $table->dropColumn('p_content_12');
            $table->dropColumn('p_content_13');
            $table->dropColumn('p_content_14');
            $table->dropColumn('p_content_15');
            $table->dropColumn('p_content_16');
            $table->dropColumn('p_content_17');
            $table->dropColumn('p_content_18');
            $table->dropColumn('p_content_19');
            $table->dropColumn('p_content_20');
            $table->dropColumn('icon_content_1');
            $table->dropColumn('icon_content_2');
            $table->dropColumn('icon_content_3');
            $table->dropColumn('icon_content_4');
            $table->dropColumn('icon_content_5');
            $table->dropColumn('icon_content_6');
            $table->dropColumn('icon_content_7');
            $table->dropColumn('icon_content_8');
            $table->dropColumn('icon_content_9');
            $table->dropColumn('icon_content_10');
            $table->dropColumn('icon_content_11');
            $table->dropColumn('icon_content_12');
            $table->dropColumn('icon_content_13');
            $table->dropColumn('icon_content_14');
            $table->dropColumn('icon_content_15');
            $table->dropColumn('icon_content_16');
            $table->dropColumn('icon_content_17');
            $table->dropColumn('icon_content_18');
            $table->dropColumn('icon_content_19');
            $table->dropColumn('icon_content_20');

            $table->dropColumn('p_cards');
            $table->dropColumn('img_items');
            $table->dropColumn('img_items_430');
            $table->dropColumn('img_items_title');
            $table->dropColumn('h2_faq');
            $table->dropColumn('p_faq');
            $table->dropColumn('h2_details');
            $table->dropColumn('p_details');
            $table->dropColumn('h3_details_1');
            $table->dropColumn('h3_details_2');
            $table->dropColumn('h3_details_3');
            $table->dropColumn('h3_details_4');
            $table->dropColumn('h3_details_5');
            $table->dropColumn('h3_details_6');
            $table->dropColumn('h3_details_7');
            $table->dropColumn('h3_details_8');
            $table->dropColumn('h3_details_9');
            $table->dropColumn('h3_details_10');
            $table->dropColumn('contnent_details_1');
            $table->dropColumn('contnent_details_2');
            $table->dropColumn('contnent_details_3');
            $table->dropColumn('contnent_details_4');
            $table->dropColumn('contnent_details_5');
            $table->dropColumn('contnent_details_6');
            $table->dropColumn('contnent_details_7');
            $table->dropColumn('contnent_details_8');
            $table->dropColumn('contnent_details_9');
            $table->dropColumn('contnent_details_10');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('chasseurs', function (Blueprint $table) {
            $table->text('h2_content')->nullable();
            $table->text('p_content')->nullable();
            $table->text('h3_content_1')->nullable();
            $table->text('h3_content_2')->nullable();
            $table->text('h3_content_3')->nullable();
            $table->text('h3_content_4')->nullable();
            $table->text('h3_content_5')->nullable();
            $table->text('h3_content_6')->nullable();
            $table->text('h3_content_7')->nullable();
            $table->text('h3_content_8')->nullable();
            $table->text('h3_content_9')->nullable();
            $table->text('h3_content_10')->nullable();
            $table->text('h3_content_11')->nullable();
            $table->text('h3_content_12')->nullable();
            $table->text('h3_content_13')->nullable();
            $table->text('h3_content_14')->nullable();
            $table->text('h3_content_15')->nullable();
            $table->text('h3_content_16')->nullable();
            $table->text('h3_content_17')->nullable();
            $table->text('h3_content_18')->nullable();
            $table->text('h3_content_19')->nullable();
            $table->text('h3_content_20')->nullable();
            $table->text('p_content_1')->nullable();
            $table->text('p_content_2')->nullable();
            $table->text('p_content_3')->nullable();
            $table->text('p_content_4')->nullable();
            $table->text('p_content_5')->nullable();
            $table->text('p_content_6')->nullable();
            $table->text('p_content_7')->nullable();
            $table->text('p_content_8')->nullable();
            $table->text('p_content_9')->nullable();
            $table->text('p_content_10')->nullable();
            $table->text('p_content_11')->nullable();
            $table->text('p_content_12')->nullable();
            $table->text('p_content_13')->nullable();
            $table->text('p_content_14')->nullable();
            $table->text('p_content_15')->nullable();
            $table->text('p_content_16')->nullable();
            $table->text('p_content_17')->nullable();
            $table->text('p_content_18')->nullable();
            $table->text('p_content_19')->nullable();
            $table->text('p_content_20')->nullable();
            $table->text('icon_content_1')->nullable();
            $table->text('icon_content_2')->nullable();
            $table->text('icon_content_3')->nullable();
            $table->text('icon_content_4')->nullable();
            $table->text('icon_content_5')->nullable();
            $table->text('icon_content_6')->nullable();
            $table->text('icon_content_7')->nullable();
            $table->text('icon_content_8')->nullable();
            $table->text('icon_content_9')->nullable();
            $table->text('icon_content_10')->nullable();
            $table->text('icon_content_11')->nullable();
            $table->text('icon_content_12')->nullable();
            $table->text('icon_content_13')->nullable();
            $table->text('icon_content_14')->nullable();
            $table->text('icon_content_15')->nullable();
            $table->text('icon_content_16')->nullable();
            $table->text('icon_content_17')->nullable();
            $table->text('icon_content_18')->nullable();
            $table->text('icon_content_19')->nullable();
            $table->text('icon_content_20')->nullable();

            $table->text('p_cards')->nullable();
            $table->text('img_items')->nullable();
            $table->text('img_items_430')->nullable();
            $table->text('img_items_title')->nullable();
            $table->text('h2_faq')->nullable();
            $table->text('p_faq')->nullable();
            $table->text('h2_details')->nullable();
            $table->text('p_details')->nullable();
            $table->text('h3_details_1')->nullable();
            $table->text('h3_details_2')->nullable();
            $table->text('h3_details_3')->nullable();
            $table->text('h3_details_4')->nullable();
            $table->text('h3_details_5')->nullable();
            $table->text('h3_details_6')->nullable();
            $table->text('h3_details_7')->nullable();
            $table->text('h3_details_8')->nullable();
            $table->text('h3_details_9')->nullable();
            $table->text('h3_details_10')->nullable();
            $table->text('contnent_details_1')->nullable();
            $table->text('contnent_details_2')->nullable();
            $table->text('contnent_details_3')->nullable();
            $table->text('contnent_details_4')->nullable();
            $table->text('contnent_details_5')->nullable();
            $table->text('contnent_details_6')->nullable();
            $table->text('contnent_details_7')->nullable();
            $table->text('contnent_details_8')->nullable();
            $table->text('contnent_details_9')->nullable();
            $table->text('contnent_details_10')->nullable();
        });
    }
}
