<table>
    <caption style="margin-bottom:15px;">{!! $data['content']->p_items_desc !!}</caption>

    <thead>
        <tr>
            <th>Ville</th>
            <th>Rénové Min<br> € / m2</th>
            <th>Rénové Max<br> € / m2</th>
            <th>Loyer par Mois<br> € / m2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Brie-Comte-Robert</td>
            <td>2920</td>
            <td>3620</td>
            <td>17,3</td>
        </tr>
        <tr>
            <td>Combs-la-Ville</td>
            <td>2000</td>
            <td>2960</td>
            <td>15,7</td>
        </tr>
        <tr>
            <td>Coulommiers</td>
            <td>2340</td>
            <td>3720</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Dammarie-les-Lys</td>
            <td>2350</td>
            <td>3720</td>
            <td>15.9</td>
        </tr>
        <tr>
            <td>Le Vésinet</td>
            <td>4710</td>
            <td>5660</td>
            <td>20.6</td>
        </tr>
        <tr>
            <td>Fontainebleau</td>
            <td>3190</td>
            <td>4160</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Lagny-sur-Marne</td>
            <td>2340</td>
            <td>3730</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Meaux</td>
            <td>2340</td>
            <td>3720</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Melun</td>
            <td>2210</td>
            <td>3250</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Nemours</td>
            <td>2350</td>
            <td>3730</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Ozoir-la-Ferrière</td>
            <td>3180</td>
            <td>4090</td>
            <td>17,0</td>
        </tr>
        <tr>
            <td>Pontault-Combault</td>
            <td>3240</td>
            <td>4100</td>
            <td>18,7</td>
        </tr>
        <tr>
            <td>Provins</td>
            <td>2350</td>
            <td>3720</td>
            <td>15,9</td>
        </tr>
        <tr>
            <td>Vert-Saint-Denis</td>
            <td>2870</td>
            <td>3610</td>
            <td>17,1</td>
        </tr>
    </tbody>
</table>