<table>
    <caption style="margin-bottom:15px;">{!! $data['content']->p_items_desc !!}</caption>

    <thead>
        <tr>
            <th>Ville</th>
            <th>Rénové Min<br> € / m2</th>
            <th>Rénové Max<br> € / m2</th>
            <th>Loyer par Mois<br> € / m2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Conflans-Sainte-Honorine</td>
            <td>2650</td>
            <td>3810</td>
            <td>16,3</td>
        </tr>
        <tr>
            <td>Fontenay-le-Fleury</td>
            <td>2510</td>
            <td>3730</td>
            <td>16,9</td>
        </tr>
        <tr>
            <td>La-Celle-Saint-Cloud</td>
            <td>3410</td>
            <td>4050</td>
            <td>17,0</td>
        </tr>
        <tr>
            <td>Le Chesnay</td>
            <td>4710</td>
            <td>5660</td>
            <td>18.3</td>
        </tr>
        <tr>
            <td>Le Vésinet</td>
            <td>4710</td>
            <td>5660</td>
            <td>20.6</td>
        </tr>
        <tr>
            <td>Maison-Lafitte</td>
            <td>5230</td>
            <td>7300</td>
            <td>20,8</td>
        </tr>
        <tr>
            <td>Mantes-la-Jolie</td>
            <td>2990</td>
            <td>5140</td>
            <td>18,3</td>
        </tr>
        <tr>
            <td>Marly-le-Roi</td>
            <td>2990</td>
            <td>5130</td>
            <td>18,3</td>
        </tr>
        <tr>
            <td>Montigny-le-Bretonneux</td>
            <td>3330</td>
            <td>4200</td>
            <td>17,3</td>
        </tr>
        <tr>
            <td>Rambouillet</td>
            <td>2240</td>
            <td>2310</td>
            <td>18,3</td>
        </tr>
        <tr>
            <td>Saint-Germain-en-Laye</td>
            <td>4480</td>
            <td>7180</td>
            <td>23,3</td>
        </tr>
        <tr>
            <td>Saint-Rémy-lès-Chevreuse</td>
            <td>2990</td>
            <td>5140</td>
            <td>18,3</td>
        </tr>
        <tr>
            <td>Versailles</td>
            <td>5960</td>
            <td>8010</td>
            <td>23,2</td>
        </tr>
        <tr>
            <td>Viroflay</td>
            <td>5250</td>
            <td>6360</td>
            <td>21,0</td>
        </tr>
    </tbody>
</table>