<table class="supply__table">
    <caption style="margin-bottom:15px;">{!! $data['content']->p_items_desc !!}</caption>

            <thead>
                <tr>
                    <th>Ville</th>
                    <th>À rénover<br>€ / m2</th>
                    <th>Rénové<br>€ / m2</th>
                    <th>Haut de Gamme<br>€ / m2</th>
                    <th>Loyer par Mois<br>€ / m2</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Aubervilliers</td>
                    <td>3330</td>
                    <td>4130</td>
                    <td>4480</td>
                    <td>17,9</td>
                </tr>
                <tr>
                    <td>Bagnolet</td>
                    <td>3960</td>
                    <td>4800</td>
                    <td>5410</td>
                    <td>20,4</td>
                </tr>
                <tr>
                    <td>Bobigny</td>
                    <td>2880</td>
                    <td>3480</td>
                    <td>3650</td>
                    <td>17,6</td>
                </tr>
                <tr>
                    <td>Clichy-sous-Bois</td>
                    <td>1660</td>
                    <td>1990</td>
                    <td>2400</td>
                    <td>19,0</td>
                </tr>
                <tr>
                    <td>La Courneuve</td>
                    <td>2400</td>
                    <td>2990</td>
                    <td>3430</td>
                    <td>23,7</td>
                </tr>
                <tr>
                    <td>Les Lilas</td>
                    <td>4500</td>
                    <td>5480</td>
                    <td>6390</td>
                    <td>20,8</td>
                </tr>
                <tr>
                    <td>Livry-Gargan</td>
                    <td>2370</td>
                    <td>2880</td>
                    <td>3370</td>
                    <td>18,6</td>
                </tr>
                <tr>
                    <td>Montreuil</td>
                    <td>4400</td>
                    <td>5850</td>
                    <td>6350</td>
                    <td>18,6</td>
                </tr>
                <tr>
                    <td>Noisy-le-Grand</td>
                    <td>3040</td>
                    <td>3840</td>
                    <td>4290</td>
                    <td>17,9</td>
                </tr>
                <tr>
                    <td>Noisy-le-Sec</td>
                    <td>2870</td>
                    <td>3610</td>
                    <td>4000</td>
                    <td>17,9</td>
                </tr>
                <tr>
                    <td>Pantin</td>
                    <td>4600</td>
                    <td>5710</td>
                    <td>6320</td>
                    <td>21,9</td>
                </tr>
                <tr>
                    <td>Le Pré Saint Gervais</td>
                    <td>5060</td>
                    <td>6000</td>
                    <td>6280</td>
                    <td>25,9</td>
                </tr>
                <tr>
                    <td>Le Raincy</td>
                    <td>3300</td>
                    <td>4020</td>
                    <td>4480</td>
                    <td>18,3</td>
                </tr>
                <tr>
                    <td>Romainville</td>
                    <td>3920</td>
                    <td>4830</td>
                    <td>5310</td>
                    <td>19,3</td>
                </tr>
                <tr>
                    <td>Rosny-sous-Bois</td>
                    <td>950</td>
                    <td>1310</td>
                    <td>1560</td>
                    <td>9,8</td>
                </tr>
                <tr>
                    <td>Saint-Denis</td>
                    <td>2980</td>
                    <td>3690</td>
                    <td>4090</td>
                    <td>19,7</td>
                </tr>
                <tr>
                    <td>Saint-Ouen</td>
                    <td>4880</td>
                    <td>5870</td>
                    <td>6430</td>
                    <td>21,4</td>
                </tr>
                <tr>
                    <td>Stains</td>
                    <td>2170</td>
                    <td>2600</td>
                    <td>2930</td>
                    <td>19,9</td>
                </tr>
                <tr>
                    <td>Villemomble</td>
                    <td>2830</td>
                    <td>3430</td>
                    <td>4040</td>
                    <td>17,8</td>
                </tr>
                <tr>
                    <td>Villepinte</td>
                    <td>1960</td>
                    <td>2510</td>
                    <td>3090</td>
                    <td>15,1</td>
                </tr>
                <tr>
                    <td>Villetaneuse</td>
                    <td>2140</td>
                    <td>2560</td>
                    <td>2960</td>
                    <td>19,0</td>
                </tr>
            </tbody>
        </table>