<table>
    <caption style="margin-bottom:15px;">{!! $data['content']->p_items_desc !!}</caption>

            <thead>
                <tr>
                    <th>Ville</th>
                    <th>À rénover<br>€ / m2</th>
                    <th>Rénové<br>€ / m2</th>
                    <th>Haut de Gamme<br>€ / m2</th>
                    <th>Loyer par Mois<br>€ / m2</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Alfortville</td>
                    <td>4240</td>
                    <td>5060</td>
                    <td>5410</td>
                    <td>20,8</td>
                </tr>
                <tr>
                    <td>Arcueil</td>
                    <td>4720</td>
                    <td>5690</td>
                    <td>6150</td>
                    <td>23,2</td>
                </tr>
                <tr>
                    <td>Boissy-Saint-Léger</td>
                    <td>2180</td>
                    <td>2760</td>
                    <td>3490</td>
                    <td>16,1</td>
                </tr>
                <tr>
                    <td>Bonneuil-sur-Marne</td>
                    <td>2700</td>
                    <td>3220</td>
                    <td>3740</td>
                    <td>19,8</td>
                </tr>
                <tr>
                    <td>Bry-sur-Marne</td>
                    <td>3910</td>
                    <td>4790</td>
                    <td>5340</td>
                    <td>18,2</td>
                </tr>
                <tr>
                    <td>Cachan</td>
                    <td>4290</td>
                    <td>5150</td>
                    <td>5650</td>
                    <td>21,5</td>
                </tr>
                <tr>
                    <td>Champigny-sur-Marne</td>
                    <td>2840</td>
                    <td>3480</td>
                    <td>3960</td>
                    <td>18,3</td>
                </tr>
                <tr>
                    <td>Charenton-le-Pont</td>
                    <td>6580</td>
                    <td>7870</td>
                    <td>8920</td>
                    <td>25,3</td>
                </tr>
                <tr>
                    <td>Créteil</td>
                    <td>2900</td>
                    <td>3530</td>
                    <td>4270</td>
                    <td>18,6</td>
                </tr>
                <tr>
                    <td>Fontenay-sous-Bois</td>
                    <td>4610</td>
                    <td>5580</td>
                    <td>6000</td>
                    <td>24,9</td>
                </tr>
                <tr>
                    <td>Fresnes</td>
                    <td>2690</td>
                    <td>3240</td>
                    <td>3890</td>
                    <td>15,3</td>
                </tr>
                <tr>
                    <td>Gentilly</td>
                    <td>4630</td>
                    <td>5280</td>
                    <td>5730</td>
                    <td>22,8</td>
                </tr>
                <tr>
                    <td>L'Haÿ-les-Roses</td>
                    <td>3260</td>
                    <td>3920</td>
                    <td>4680</td>
                    <td>17,7</td>
                </tr>
                <tr>
                    <td>Ivry-sur-Seine</td>
                    <td>1850</td>
                    <td>2130</td>
                    <td>2410</td>
                    <td>10,9</td>
                </tr>
                <tr>
                    <td>Joinville-le-Pont</td>
                    <td>4870</td>
                    <td>5780</td>
                    <td>6290</td>
                    <td>21,5</td>
                </tr>
                <tr>
                    <td>Le Kremlin-Bicêtre</td>
                    <td>4880</td>
                    <td>5690</td>
                    <td>5870</td>
                    <td>21,6</td>
                </tr>
                <tr>
                    <td>Maisons-Alfort</td>
                    <td>4620</td>
                    <td>5540</td>
                    <td>6020</td>
                    <td>21,5</td>
                </tr>
                <tr>
                    <td>Nogent-sur-Marne</td>
                    <td>5350</td>
                    <td>6400</td>
                    <td>6860</td>
                    <td>21,9</td>
                </tr>
                <tr>
                    <td>Saint-Mandé</td>
                    <td>7740</td>
                    <td>8990</td>
                    <td>9950</td>
                    <td>26,4</td>
                </tr>
                <tr>
                    <td>Saint-Maur-des-Fossés</td>
                    <td>4470</td>
                    <td>5710</td>
                    <td>6510</td>
                    <td>21,8</td>
                </tr>
                <tr>
                    <td>Saint-Maurice</td>
                    <td>5470</td>
                    <td>6550</td>
                    <td>6640</td>
                    <td>22,9</td>
                </tr>
                <tr>
                    <td>Villejuif</td>
                    <td>4390</td>
                    <td>5300</td>
                    <td>5720</td>
                    <td>21,5</td>
                </tr>
                <tr>
                    <td>Vincennes</td>
                    <td>7280</td>
                    <td>8700</td>
                    <td>9100</td>
                    <td>27,3</td>
                </tr>
                <tr>
                    <td>Vitry-sur-Seine</td>
                    <td>3080</td>
                    <td>3740</td>
                    <td>4240</td>
                    <td>19,8</td>
                </tr>
            </tbody>
        </table>